In [1]:
import numpy as np

In [2]:
s = np.array([
    [5,3,4,6,7,8,9,1,2],
    [6,7,2,1,9,5,3,4,6],
    [1,9,8,3,4,2,5,6,7],

    [2,7,6,1,5,9,4,3,8],
    [9,5,1,4,3,8,2,7,6],
    [4,8,3,7,2,6,1,5,9],

    [8,1,2,7,5,3,6,4,9],
    [6,5,7,1,9,4,8,2,3],
    [4,9,3,6,8,2,7,1,5]
])

# Row check
for row in s:
    if np.sum(row) != 45:
        print("Sudoku is not valid (row issue)")
        break
else:
    print("Rows are valid")

# Column check (FIXED)
for col in s.T:   # or axis=0
    if np.sum(col) != 45:
        print("Sudoku is not valid (column issue)")
        break
else:
    print("Columns are valid")

Sudoku is not valid (row issue)
Sudoku is not valid (column issue)


In [3]:
s.sum()

np.int64(403)

In [4]:
np.sum(s,axis=0)

array([45, 54, 36, 36, 52, 47, 45, 33, 55])

In [5]:
s[0:3,0:3]

array([[5, 3, 4],
       [6, 7, 2],
       [1, 9, 8]])

In [6]:
s[0:3, 6:9]

array([[9, 1, 2],
       [3, 4, 6],
       [5, 6, 7]])

In [7]:
s[0:3, 3:6]

array([[6, 7, 8],
       [1, 9, 5],
       [3, 4, 2]])

In [8]:
for i in range(0,9,3):
    for j in range(0,9,3):
        n=s[i:i+3, j:j+3]
        print(n.sum())
        

45
45
43
45
45
45
45
45
45


In [9]:
data = np.array([
    [18, 85, 78],
    [19, 92, 88],
    [17, 76, 70],
    [20, 90, 85],
    [18,65,85]
])

In [10]:
# Get the shape of the matrix
data.shape

(5, 3)

In [11]:
# find the average age of student.
np.mean(data[:,0])

np.float64(18.4)

In [12]:
#extract Math marks of all students.
data[:,1]

array([85, 92, 76, 90, 65])

In [13]:
#find the higest science mark.
np.max(data[0:,2])

np.int64(88)

In [14]:
# get details of the student who scored more than 90 in Math
data[data[:,1]> 90]

array([[19, 92, 88]])

In [15]:
data

array([[18, 85, 78],
       [19, 92, 88],
       [17, 76, 70],
       [20, 90, 85],
       [18, 65, 85]])

In [16]:
# increase Math marks of all students by 5
data[0:,1]+=5
data

array([[18, 90, 78],
       [19, 97, 88],
       [17, 81, 70],
       [20, 95, 85],
       [18, 70, 85]])

In [17]:
# find how many studets are younger than 19
len(data [data[:,0]<19])

3

In [18]:
# claculate the average marks in each subject (colume-wise mean)
np.mean(data[:,1:], axis=0)

array([86.6, 81.2])

In [19]:
# get data of student who scored at least 80 in both subject
data[(data[:,1]>= 80) & (data[:,2] >= 80)]

array([[19, 97, 88],
       [20, 95, 85]])

In [20]:
data

array([[18, 90, 78],
       [19, 97, 88],
       [17, 81, 70],
       [20, 95, 85],
       [18, 70, 85]])

In [21]:
# replace all science marks < 75 with 0
data[:,2][data[:,2]<75]=0
data

array([[18, 90, 78],
       [19, 97, 88],
       [17, 81,  0],
       [20, 95, 85],
       [18, 70, 85]])