In [9]:
import numpy as np

In [11]:
arr = np.array([1,2,3,4,5])
arr

array([1, 2, 3, 4, 5])

In [12]:
a =[1,2,3.4]
a

[1, 2, 3.4]

In [13]:
np.array(a)

array([1. , 2. , 3.4])

In [14]:
l = [[1,2,3],[4,5,6],[7,8,9]]
l

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [15]:
np.array(l)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [16]:
np.arange(1,10)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [17]:
np.arange(1,10,2)

array([1, 3, 5, 7, 9])

In [21]:
arr=np.zeros(6)
arr
arr2=np.zeros((4,8))
arr2

array([[0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.]])

In [24]:
arr=np.ones((6,6))
arr

array([[1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1.]])

In [29]:
arr = np.linspace(1,5,5)
arr
arr2 =np.linspace(1,5,3)
arr2

array([1., 3., 5.])

In [30]:
np.random.rand(5)

array([0.84007151, 0.9041617 , 0.28095473, 0.5291945 , 0.65350557])

In [31]:
np.random.randint(10,20,10)

array([16, 11, 17, 17, 16, 11, 11, 11, 11, 14], dtype=int32)

In [32]:
# Array Attributes
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [33]:
arr.shape

(3, 3)

In [34]:
arr.size

9

In [35]:
arr.dtype

dtype('int64')

In [36]:
# Array Method
arr.min()

np.int64(1)

In [37]:
arr.max()

np.int64(9)

In [38]:
arr.sum()

np.int64(45)

In [40]:
np.sum(arr, axis=0) #coll
np.sum(arr, axis=1) #row

array([ 6, 15, 24])

In [41]:
arr.mean()

np.float64(5.0)

In [42]:
arr.std()

np.float64(2.581988897471611)

In [43]:
arr.argmax()

np.int64(8)

In [44]:
arr.argmin()

np.int64(0)

In [49]:
# Reshaping and resizing
arr = np.arange(1,31)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [51]:
arr = arr.reshape(6,5)
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [55]:
# Numpy indexing and slicing of vectors
arr =np.arange(11,21)
arr

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [56]:
arr[2]

np.int64(13)

In [57]:
arr[1:4]

array([12, 13, 14])

In [58]:
arr[:5]

array([11, 12, 13, 14, 15])

In [59]:
arr[:]

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [60]:
arr[3:]

array([14, 15, 16, 17, 18, 19, 20])

In [61]:
arr[3::2]

array([14, 16, 18, 20])

In [62]:
arr[4]

np.int64(15)

In [65]:
# Numpy indexing and slicing of matrix
arr = np.arange(1,31).reshape(6,5)
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [66]:
arr[0]

array([1, 2, 3, 4, 5])

In [67]:
arr[1]

array([ 6,  7,  8,  9, 10])

In [69]:
arr[5]

array([26, 27, 28, 29, 30])

In [71]:
arr[0,0]

np.int64(1)

In [72]:
arr[0,4]

np.int64(5)

In [73]:
arr[5,4]

np.int64(30)

In [74]:
arr[0:2, 1:3] #slice

array([[2, 3],
       [7, 8]])

In [77]:
arr[3:, 3:]

array([[19, 20],
       [24, 25],
       [29, 30]])

In [78]:
arr[:,2]

array([ 3,  8, 13, 18, 23, 28])

In [79]:
# boolean indexing

In [81]:
arr=np.arange(11,21)
arr

array([11, 12, 13, 14, 15, 16, 17, 18, 19, 20])

In [83]:
bool_index = arr % 2 == 0
bool_index

array([False,  True, False,  True, False,  True, False,  True, False,
        True])

In [84]:
arr = arr[bool_index]
arr

array([12, 14, 16, 18, 20])

In [85]:
# Array operatons
# advance array Manipulation

In [90]:
# Array operatons
a1 = np.array([1,2,3,4,5])
a2 = np.array([6,7,8,9,10])

In [91]:
a1 + a2

array([ 7,  9, 11, 13, 15])

In [92]:
a1 - a2

array([-5, -5, -5, -5, -5])

In [93]:
a1 * a2

array([ 6, 14, 24, 36, 50])

In [94]:
a1 / a2

array([0.16666667, 0.28571429, 0.375     , 0.44444444, 0.5       ])

In [95]:
a1 // a2

array([0, 0, 0, 0, 0])

In [96]:
a1 ** a2

array([      1,     128,    6561,  262144, 9765625])

In [97]:
# Broadcasting 
l = [10,20,30,40]
arr = np.array(l)

In [98]:
arr + 10

array([20, 30, 40, 50])

In [100]:
arr2 = np.arange(1,26).reshape(5,5)
arr2

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [101]:
arr2 + 10

array([[11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35]])

In [104]:
# Deep and shallow copy
a =np.arange(1,21)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [106]:
slice = a[:5]
slice

array([1, 2, 3, 4, 5])

In [107]:
slice * 10

array([10, 20, 30, 40, 50])

In [111]:
a #shallow copy

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [115]:
a
b=a

In [116]:
b[0]= 99

In [117]:
a

array([99,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [119]:
# Matrix operations
a = np.array([[1,2],[3,4]])
b = np.array([[5,6],[7,8]])

In [121]:
a @ b

array([[19, 22],
       [43, 50]])

In [123]:
np.dot(a,b)

array([[19, 22],
       [43, 50]])

In [124]:
a

array([[1, 2],
       [3, 4]])

In [125]:
a.T # tranfore

array([[1, 3],
       [2, 4]])

In [131]:
# Stacking Array
a = np.array([1,2,3,4])
b = np.array([5,6,7,8])
a

array([1, 2, 3, 4])

In [128]:
b

array([[5, 6],
       [7, 8]])

In [132]:
np.vstack((a,b))

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [133]:
np.hstack((a,b))

array([1, 2, 3, 4, 5, 6, 7, 8])

In [134]:
np.column_stack((a,b))

array([[1, 5],
       [2, 6],
       [3, 7],
       [4, 8]])

In [136]:
# splitting array 
c = np.arange(16).reshape(4,4)
c

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [137]:
np.hsplit(c,2)

[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]

In [138]:
np.vsplit(c,2)

[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]