In [1]:
import numpy as np

In [3]:
a = np.arange(1,13)
print(a)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [9]:
convert_into=a.reshape(3,4)
print("reshaping 3 X 4" ,convert_into)

reshaping 3 X 4 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [10]:
reshape = a.reshape(4,3)
print("Reshaping 4 X 3 :", reshape)

Reshaping 4 X 3 : [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]
