In [1]:
import numpy as np

In [8]:

a =np.zeros((3,3))
print("Shape: ",a.shape)
print(a)

Shape:  (3, 3)
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [10]:
a =np.ones((2,4))
print("Shape: ", a.shape)

Shape:  (2, 4)


In [11]:
a =np.eye(4)
print("Shape: ",a.shape)

Shape:  (4, 4)


In [12]:
a = np.arange(1,11)
print("Shape: ", a.shape)

Shape:  (10,)
