In [1]:
import numpy as np

In [2]:
a1 = np.array([1,2,3,4,5])
a2 = np.array([6,7,8,9,10])

In [3]:
a1 + a2 #Arithmatic operators 

array([ 7,  9, 11, 13, 15])

In [5]:
# Broadcasting 
l = [10,20,30,40]
arr = np.array(l)

In [6]:
arr + 10

array([20, 30, 40, 50])

In [7]:
# Deep and Shallow copy
a = np.arange(1,21)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [12]:
slice = a[:5]
slice = slice *10
slice #shallow copy

array([10, 20, 30, 40, 50])

In [13]:
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [14]:
# deep copy
b =a
b 

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [16]:
b[0]=99
b

array([99,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [17]:
a

array([99,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [25]:
a
c =a.copy()


In [26]:
c[0]=1

In [27]:
a

array([99,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [28]:
c

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [29]:
# Matrix Operation 
mat1 =np.array([[1,2],[3,4]])
mat2 = np.array([[5,6],[7,8]])

In [30]:
mat1

array([[1, 2],
       [3, 4]])

In [31]:
mat2

array([[5, 6],
       [7, 8]])

In [32]:
mat1 @ mat2

array([[19, 22],
       [43, 50]])

In [35]:
np.dot(mat1,mat2)

array([[19, 22],
       [43, 50]])