In [1]:
import numpy as np

In [2]:
arr = np.arange(12,21)
arr

array([12, 13, 14, 15, 16, 17, 18, 19, 20])

In [3]:
arr[1] #access element

np.int64(13)

In [4]:
arr[2:4]

array([14, 15])

In [5]:
arr[:6] # start default value 0 i not assign

array([12, 13, 14, 15, 16, 17])

In [6]:
arr[4:] # if not assign end is automatically last index

array([16, 17, 18, 19, 20])

In [7]:
arr[:]

array([12, 13, 14, 15, 16, 17, 18, 19, 20])

In [8]:
arr[2::2]

array([14, 16, 18, 20])

In [9]:
arr= np.arange(1,31).reshape(6,5)
arr

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [10]:
arr[0] # Target rows 

array([1, 2, 3, 4, 5])

In [11]:
arr[:,0] # Target 0 index column value

array([ 1,  6, 11, 16, 21, 26])

In [12]:
arr[0:2,1:3]

array([[2, 3],
       [7, 8]])

In [13]:
arr[3:,3:]

array([[19, 20],
       [24, 25],
       [29, 30]])

In [14]:
arr[3:6,2]

array([18, 23, 28])

In [15]:
arr = np.arange(10,81,10)
arr

array([10, 20, 30, 40, 50, 60, 70, 80])

In [16]:
arr[0]

np.int64(10)

In [17]:
arr[7]

np.int64(80)

In [18]:
arr[0:4]

array([10, 20, 30, 40])

In [19]:
arr[5:]

array([60, 70, 80])

In [20]:
arr[2:6]

array([30, 40, 50, 60])

In [21]:
arr[::2]

array([10, 30, 50, 70])

In [22]:
arr[1:7:2]

array([20, 40, 60])

In [23]:
arr[::-1]

array([80, 70, 60, 50, 40, 30, 20, 10])

In [24]:
arr[::3]

array([10, 40, 70])

In [25]:
arr[0:-1]

array([10, 20, 30, 40, 50, 60, 70])

In [28]:
arr[-1:-6:-1] #arr[start : stop : step]

array([80, 70, 60, 50, 40])

In [29]:
arr[1:5]

array([20, 30, 40, 50])

In [30]:
arr=np.arange(1,21)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [31]:
arr[1::2]

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [34]:
arr=np.random.randint(1,21,20)
arr

array([20, 17, 17, 20, 16,  9, 14, 20, 20,  4,  4, 10, 13, 19,  2,  1, 17,
        5,  1,  4], dtype=int32)

In [36]:
arr[arr % 2 !=0]

array([17, 17,  9, 13, 19,  1, 17,  5,  1], dtype=int32)

In [37]:
arr[arr % 2 ==0]

array([20, 20, 16, 14, 20, 20,  4,  4, 10,  2,  4], dtype=int32)

In [39]:
arr = np.arange(1,21)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20])

In [40]:
arr[0::2]

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19])

In [41]:
arr[1::2]

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [48]:
arr[-5:-1]

array([16, 17, 18, 19])