In [1]:
import numpy as np

In [2]:
# Basic Array Creation
arr= np.array([1,2,3,4,5])

In [3]:
arr

array([1, 2, 3, 4, 5])

In [4]:
a = [1,2,3,4,"Nishan"] #List 

In [5]:
np.array(a) #Convert list to array single data type 

array(['1', '2', '3', '4', 'Nishan'], dtype='<U21')

In [6]:
l =[[1,2,3],[4,5,6],[7,8,9]]

In [7]:
np.array(l)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [8]:
# array generation function 
np.arange(1,11)

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [9]:
np.arange(1,11,2)

array([1, 3, 5, 7, 9])

In [10]:
arr= np.zeros(6)

In [11]:
arr

array([0., 0., 0., 0., 0., 0.])

In [12]:
arr=np.zeros((4,8))

In [13]:
arr

array([[0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0.]])

In [14]:
arr = np.ones((5,5))

In [15]:
arr

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [16]:
arr = np.linspace(1,5,2)
arr

array([1., 5.])

In [17]:
arr= np.linspace(1,5,3)
arr

array([1., 3., 5.])

In [18]:
arr= np.linspace(0,1,100)
arr

array([0.        , 0.01010101, 0.02020202, 0.03030303, 0.04040404,
       0.05050505, 0.06060606, 0.07070707, 0.08080808, 0.09090909,
       0.1010101 , 0.11111111, 0.12121212, 0.13131313, 0.14141414,
       0.15151515, 0.16161616, 0.17171717, 0.18181818, 0.19191919,
       0.2020202 , 0.21212121, 0.22222222, 0.23232323, 0.24242424,
       0.25252525, 0.26262626, 0.27272727, 0.28282828, 0.29292929,
       0.3030303 , 0.31313131, 0.32323232, 0.33333333, 0.34343434,
       0.35353535, 0.36363636, 0.37373737, 0.38383838, 0.39393939,
       0.4040404 , 0.41414141, 0.42424242, 0.43434343, 0.44444444,
       0.45454545, 0.46464646, 0.47474747, 0.48484848, 0.49494949,
       0.50505051, 0.51515152, 0.52525253, 0.53535354, 0.54545455,
       0.55555556, 0.56565657, 0.57575758, 0.58585859, 0.5959596 ,
       0.60606061, 0.61616162, 0.62626263, 0.63636364, 0.64646465,
       0.65656566, 0.66666667, 0.67676768, 0.68686869, 0.6969697 ,
       0.70707071, 0.71717172, 0.72727273, 0.73737374, 0.74747

In [19]:
# random generation function 
np.random.rand(5)

array([0.22447725, 0.64879243, 0.40031062, 0.24128705, 0.48052489])

In [20]:
np.random.randint(6)

0

In [21]:
np.random.randint(10,20,10)

array([18, 14, 11, 19, 17, 13, 15, 11, 18, 16], dtype=int32)

In [22]:
# array Attributes
arr =np.array([[1, 2, 3],
               [4, 5, 6],
            [7, 8, 9],
    [10, 11, 12]])
arr

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [23]:
arr.shape

(4, 3)

In [24]:
arr.size

12

In [25]:
arr.dtype

dtype('int64')

In [26]:
# array methods
arr.min()

np.int64(1)

In [27]:
arr.max()

np.int64(12)

In [28]:
arr.sum()

np.int64(78)

In [29]:
np.sum(arr, axis=0)

array([22, 26, 30])

In [30]:
np.sum(arr, axis=1)

array([ 6, 15, 24, 33])

In [31]:
arr.mean()

np.float64(6.5)

In [32]:
arr.std()

np.float64(3.452052529534663)

In [33]:
arr.argmax()

np.int64(11)

In [34]:
arr.argmin()

np.int64(0)

In [35]:
# Reshaping and resizing
arr =np.arange(1,31)
arr

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [36]:
arr.reshape(6,5)

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30]])

In [37]:
# Numpy indexing and slicing of vectors
index= np.arange(11,21)
print(index)


[11 12 13 14 15 16 17 18 19 20]


In [38]:
bool_index= index % 2 ==0
bool_index

array([False,  True, False,  True, False,  True, False,  True, False,
        True])

In [41]:
arr =index[bool_index]
arr

array([12, 14, 16, 18, 20])

In [ ]:
# Numpy indexing and slicing of Matrix

In [ ]:
# Boolean indexing